version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every weekday
    interval: "daily"
    time: "03:22"
  assignees:
  - pfichtner
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "daily"
    time: "03:22"
  assignees:
  - pfichtner
  ignore:
    - dependency-name: "org.junit.jupiter:junit-jupiter"
      versions: [">=6.0.0"]

    - dependency-name: "nl.jqno.equalsverifier:equalsverifier"
      versions: [">=4.0.0"]
